version: 0.2
phases:
  install:
    commands:
      - command
      - command
    finally:
      - command
      - command
  pre_build:
    commands:
      - command
      - command
    finally:
      - command
      - command
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - docker build -t learn-codebuild:${CODEBUILD_RESOLVED_SOURCE_VERSION} .
      - docker tag learn-codebuild:${CODEBUILD_RESOLVED_SOURCE_VERSION} 486555357186.dkr.ecr.eu-west-1.amazonaws.com/learn-codebuild-andreas:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push 486555357186.dkr.ecr.eu-west-1.amazonaws.com/learn-codebuild-andreas:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - command
    finally:
      - command
      - command
  post_build:
    commands:
      - command
      - command
    finally:
      - command
      - command
# artifacts:
#   files:
#     - location
#     - location
#     - name
#   discard-paths: yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
