version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - docker build -t learn-codebuild:${CODEBUILD_RESOLVED_SOURCE_VERSION} .
      - $(aws ecr get-login --no-include-email)
      - docker tag learn-codebuild:${CODEBUILD_RESOLVED_SOURCE_VERSION} 486555357186.dkr.ecr.eu-west-1.amazonaws.com/learn-codebuild-andreas:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push 486555357186.dkr.ecr.eu-west-1.amazonaws.com/learn-codebuild-andreas:${CODEBUILD_RESOLVED_SOURCE_VERSION}
